Repository atlp-rwanda/champs-ec-be, pull requests merged in 2024-05, with the labels that each got.

#49 Fixed the bug for migration and demigration on every test command.
  .env.example
  package-lock.json
  package.json
  src/__test__/initial.spec.ts
  src/controllers/cart.controller.ts
  src/middlewares/productCategory.middlewares.ts
  src/utils/cartMergeProduct.ts
  tsconfig.json
Labels: bug, Ready for review

#51 Add additional fields for seller and buyer in wishlist
  package-lock.json
  src/__test__/initial.spec.ts
  src/controllers/user.controllers.ts
  src/controllers/wish.controller.ts
  src/database/migrations/20240408160241-blacklisted_tokens.js
  src/database/migrations/20240428201228-notification.js
  src/database/migrations/20240501152533-chat-room.js
  src/middlewares/user.auth.ts
  src/routes/product.routes.ts
  src/routes/wish.routes.ts
  src/services/wish.services.ts
  swagger.json
Labels: enhancement, Ready for review

#53 ##187300263 implementation of stripe payment api
  champs-ec-be.code-workspace
  package-lock.json
  package.json
  src/__test__/disable-account.spec.ts
  src/__test__/initial.spec.ts
  src/__test__/order.spec.ts
  src/app.ts
  src/controllers/orderControllers.ts
  src/controllers/payment.controllers.ts
  src/controllers/product.controllers.ts
  src/database/migrations/20240401161515-products.js
  src/database/migrations/20240428150433-create-order.js
  src/database/seeders/20240325212203-user.js
  src/database/seeders/20240411093719-dummy_users.js
  src/database/seeders/20240413145848-products.js
  src/middlewares/sellerproduct.middlewares.ts
  src/models/Order.ts
  src/models/Product.ts
  src/routes/orders.routes.ts
  src/routes/payment.routes.ts
  src/services/payment.services.ts
  src/types/order.types.ts
  src/types/product.types.ts
  src/validations/order.validation.ts
  swagger.json
Labels: Ready for review

#55 Adding if purchased a product is when allowed to review
  src/__test__/initial.spec.ts
  src/__test__/otpauth.spec.ts
  src/controllers/product.controllers.ts
  src/controllers/reviews.controller.ts
  src/middlewares/reviews.middlewares.ts
  src/middlewares/user.auth.ts
Labels: Ready for review

#57 Ft tracking order status #187300262
  src/__test__/initial.spec.ts
  src/controllers/orderControllers.ts
  src/routes/orders.routes.ts
  swagger.json
Labels: enhancement, WIP, Ready for review

#58 Ft stats #187504894
  .vscode/settings.json
  package-lock.json
  package.json
  src/__test__/stats.spec.ts
  src/app.ts
  src/controllers/payment.controllers.ts
  src/controllers/product.controllers.ts
  src/controllers/reviews.controller.ts
  src/controllers/stats.controller.ts
  src/controllers/wish.controller.ts
  src/cronjobs/crontab.ts
  src/middlewares/role.middleware.ts
  src/models/champs-ec-be.code-workspace
  src/routes/stats.routes.ts
  src/validations/sellerProduct.validation.ts
  src/validations/stats.validations.ts
  swagger.json
Labels: Ready for review

#59 #187300268 user Notification with node events and socket.io
  package.json
  public/index.html
  public/notification.html
  public/notification.js
  public/script.js
  public/style.css
  src/__test__/cronJobs/Products/startCron.spec.ts
  src/__test__/initial.spec.ts
  src/__test__/order.spec.ts
  src/app.ts
  src/config/db.config.ts
  src/controllers/notification.controller.ts
  src/controllers/orderControllers.ts
  src/controllers/payment.controllers.ts
  src/controllers/product.controllers.ts
  src/controllers/wish.controller.ts
  src/cronjobs/crontab.ts
  src/middlewares/productCategory.middlewares.ts
  src/models/Notifications.ts
  src/models/user.ts
  src/routes/notification.routes.ts
  src/server.ts
  src/services/eventEmit.services.ts
  src/socket.notification.ts
  src/socketServer.ts
  src/types/notification.types.ts
  src/utils/mailer.ts
  src/utils/search.ts
  swagger.json
Labels: enhancement, Ready for review

#60 #187527339 Feature Product
  .env.example
  package-lock.json
  src/__test__/initial.spec.ts
  src/controllers/product.controllers.ts
  src/cronjobs/crontab.ts
  src/database/migrations/20240401161515-products.js
  src/database/seeders/20240411093719-dummy_users.js
  src/database/seeders/20240413145848-products.js
  src/models/Product.ts
  src/routes/product.routes.ts
  src/types/product.types.ts
  src/utils/finders.ts
  swagger.json
Labels: Ready for review

#56 #187514252 Listing related products & seller info
  .DS_Store
  package-lock.json
  package.json
  src/config/passport.config.ts
  src/controllers/product.controllers.ts
  src/controllers/user.controllers.ts
  src/middlewares/sellerproduct.middlewares.ts
  src/models/Order.ts
  src/models/Product.ts
  src/models/product_category.ts
  swagger.json
Labels: Ready for review

#63 #187527339 Feature Product(bug fix)
  package-lock.json
  src/__test__/initial.spec.ts
  src/controllers/product.controllers.ts
  src/controllers/search.controller.ts
  src/utils/date.ts
Labels: Ready for review

#64 Bug fixing
  package-lock.json
  package.json
  public/index.html
  public/notification.html
  src/__test__/initial.spec.ts
  src/app.ts
  src/chats.ts
  src/controllers/cart.controller.ts
  src/controllers/chats.controllers.ts
  src/controllers/payment.controllers.ts
  src/database/seeders/20240325212203-user.js
  src/routes/chats.routes.ts
  src/server.ts
  src/socket.notification.ts
  src/socketServer.ts
  swagger.json
Labels: Ready for review

#66 bg-fix(cronjob firing) usershould be prompt to change their password
  package-lock.json
  src/__test__/chats.spec.ts
  src/__test__/cronJobs/Password/startCron.spec.ts
  src/app.ts
  src/config/db.config.ts
  src/controllers/chats.controllers.ts
  src/controllers/user.controllers.ts
  src/database/migrations/20240325182435-create-user.js
  src/middlewares/user.middleware.ts
  src/models/user.ts
  src/routes/chats.routes.ts
  src/routes/user.routes.ts
  src/utils/checkExpiredPassword.ts
  src/utils/extendPasswordValidity.ts
  swagger.json
Labels: bug, Ready for review
