Repository atlp-rwanda/champs-ec-be, pull requests merged in 2024-04, with the labels that each got.

#16 #187300226 Added HoundCI badges and fix ESLint errors
  .eslintrc.json
  .hound.yml
  README.md
  src/middlewares/user.auth.ts
Labels: enhancement

#17 #187300232 correct swagger for header setup
  README.md
  src/validations/user.validations.ts
  swagger.json
Labels: setting up

#20 #187300235 Verify user email after registration
  .env.example
  .gitignore
  Conventions.md
  package-lock.json
  package.json
  src/__test__/initial.spec.ts
  src/app.ts
  src/config/passport.config.ts
  src/controllers/user.controllers.ts
  src/database/migrations/20240325142734-test_migration.js
  src/database/migrations/20240325182435-create-user.js
  src/database/seeders/20240325143834-tests.js
  src/database/seeders/20240325212203-user.js
  src/models/user.ts
  src/routes/user.routes.ts
  src/server.ts
  src/types/user.types.ts
  src/utils/encrypt.ts
  src/utils/functions/logger.ts
  src/utils/functions/mailer.ts
  src/utils/functions/uploader.ts
  src/utils/mailer.ts
  src/utils/redirect.ts
  src/utils/setport.ts
  src/utils/token.generator.ts
Labels: enhancement, Ready for review

#21 #187300246. Profile Page Setting
  README.md
  image.png
  package-lock.json
  package.json
  src/__test__/image/test.jpg
  src/__test__/initial.spec.ts
  src/controllers/user.controllers.ts
  src/database/migrations/20240325182435-create-user.js
  src/database/seeders/20240325212203-user.js
  src/middlewares/user.middleware.ts
  src/models/user.ts
  src/routes/user.routes.ts
  src/types/user.types.ts
  src/utils/cloudinary.ts
  src/utils/mailer.ts
  src/utils/multer.ts
  src/validations/user.validations.ts
  swagger.json
Labels: enhancement, Ready for review

#24 #187300244 Two factor authentication
  package-lock.json
  package.json
  src/__test__/initial.spec.ts
  src/__test__/otpauth.spec.ts
  src/controllers/otpauth.controllers.ts
  src/middlewares/user.middleware.ts
  src/routes/user.routes.ts
  src/utils/mailer.ts
  src/utils/token.generator.ts
  swagger.json
Labels: Ready for review

#28 #187300248 admin can assign role to user
  package-lock.json
  package.json
  src/__test__/initial.spec.ts
  src/app.ts
  src/config/db.config.ts
  src/controllers/role.controllers.ts
  src/controllers/user.controllers.ts
  src/database/migrations/20240325172405-create-roles.js
  src/database/migrations/20240325182435-create-user.js
  src/database/seeders/20240325212203-user.js
  src/middlewares/role.middleware.ts
  src/middlewares/user.auth.ts
  src/middlewares/user.middleware.ts
  src/models/Role.ts
  src/models/user.ts
  src/routes/role.routes.ts
  src/routes/user.routes.ts
  src/types/role.types.ts
  src/types/user.types.ts
  src/utils/uuid.ts
  src/validations/role.validation.ts
  src/validations/user.validations.ts
  swagger.json
Labels: Ready for review

#33 #187300241-fix auth via google
  package.json
  src/__test__/auth.spec.ts
  src/config/google.config.ts
  src/controllers/auth.controller.ts
  src/controllers/user.controllers.ts
  src/database/migrations/20240325182435-create-user.js
  src/models/user.ts
  src/routes/auth.routes.ts
Labels: bug, Ready for review

#31 #187300246 Update the validation rules to make all fields required
  README.md
  package-lock.json
  package.json
  src/__test__/initial.spec.ts
  src/config/passport.config.ts
  src/controllers/user.controllers.ts
  src/middlewares/user.middleware.ts
  src/routes/role.routes.ts
  src/validations/user.validations.ts
Labels: bug, Ready for review

#36 #187300244 adding seller to user 2FA on login
  src/__test__/initial.spec.ts
  src/__test__/otpauth.spec.ts
  src/app.ts
  src/config/google.config.ts
  src/controllers/otpauth.controllers.ts
  src/controllers/user.controllers.ts
  src/middlewares/otpauth.middleware.ts
  src/middlewares/user.auth.ts
  src/routes/role.routes.ts
  src/routes/user.routes.ts
  src/utils/token.generator.ts
  swagger.json
Labels: bug, Ready for review

#29 #187300249 Seller CRUD operation over their products
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  src/__test__/image/20220802_165807.jpg
  src/__test__/image/JobIcon.png
  src/__test__/image/svgrepo.svg
  src/__test__/initial.spec.ts
  src/app.ts
  src/config/cloudinary.config.ts
  src/config/database.js
  src/controllers/product.controllers.ts
  src/controllers/productCategory.controllers.ts
  src/controllers/role.controllers.ts
  src/controllers/user.controllers.ts
  src/database/migrations/20240401161515-create-product-category.js
  src/database/migrations/20240401161515-products.js
  src/database/seeders/20240401161544-products.js
  src/database/seeders/20240411093719-dummy_users.js
  src/database/seeders/20240413145848-product_category.js
  src/middlewares/productCategory.middlewares.ts
  src/middlewares/role.middleware.ts
  src/middlewares/sellerproduct.middlewares.ts
  src/middlewares/user.middleware.ts
  src/models/Product.ts
  src/models/product_category.ts
  src/routes/product.routes.ts
  src/routes/productCategory.routes.ts
  src/routes/user.routes.ts
  src/types/product.types.ts
  src/types/product_category.types.ts
  src/utils/product.image.check.ts
  src/utils/string.manipulation.ts
  src/utils/uploader.ts
  src/utils/validations/user.validations.ts
  src/validations/productCategories.validations.ts
  src/validations/sellerProduct.validation.ts
  src/validations/user.validations.ts
  swagger.json
Labels: enhancement, Ready for review

#25 #187300243 Reset user password via email
  .gitignore
  package-lock.json
  package.json
  src/__test__/initial.spec.ts
  src/__test__/otpauth.spec.ts
  src/__test__/reset-password.spec.ts
  src/controllers/user.controllers.ts
  src/routes/user.routes.ts
  src/utils/finders.ts
  src/utils/token.generator.ts
  src/utils/validations/user.validations.ts
  swagger.json
Labels: Ready for review

#23 #187300239. implementing logout functionality
  .DS_Store
  src/__test__/initial.spec.ts
  src/controllers/user.controllers.ts
  src/database/migrations/20240408160241-blacklisted_tokens.js
  src/middlewares/user.auth.ts
  src/models/Blacklist.ts
  src/routes/user.routes.ts
  src/types/blacklist.types.ts
  swagger.json
Labels: enhancement, Ready for review

#37 bug(fixing-bugs): final touches
  src/__test__/initial.spec.ts
  src/controllers/user.controllers.ts
  src/middlewares/user.auth.ts
  src/utils/finders.ts
  src/validations/productCategories.validations.ts
  src/validations/role.validation.ts
  src/validations/sellerProduct.validation.ts
  src/validations/user.validations.ts
  swagger.json
Labels: bug, Ready for review

#43 #187300234 setup docker compose
  .dockerignore
  .gitignore
  Dockerfile
  docker-compose.yml
  entrypoint.sh
  src/__test__/initial.spec.ts
Labels: Ready for review

#41 #187300257 buyer is able to create a cart.
  src/__test__/initial.spec.ts
  src/app.ts
  src/config/passport.config.ts
  src/controllers/cart.controller.ts
  src/controllers/user.controllers.ts
  src/database/migrations/20240408160241-blacklisted_tokens.js
  src/database/migrations/20240417134703-create-cart.js
  src/database/seeders/20240325212203-user.js
  src/database/seeders/20240411093719-dummy_users.js
  src/database/seeders/20240413145848-products.js
  src/middlewares/checkusercart.middleware.ts
  src/models/Cart.ts
  src/routes/cart.routes.ts
  src/types/carts.types.ts
  src/utils/cartMergeProduct.ts
  src/validations/cart.validation.ts
  swagger.json
Labels: enhancement, Ready for review

#42 #187300255 Buyer's product wishlist
  .env.example
  package-lock.json
  package.json
  src/__test__/initial.spec.ts
  src/__test__/otpauth.spec.ts
  src/app.ts
  src/config/passport.config.ts
  src/controllers/product.controllers.ts
  src/controllers/user.controllers.ts
  src/controllers/wish.controller.ts
  src/database/migrations/20240408160241-blacklisted_tokens.js
  src/database/migrations/20240419062737-wish-migration.js
  src/middlewares/user.auth.ts
  src/middlewares/user.middleware.ts
  src/models/Test.ts
  src/models/Wish.ts
  src/routes/product.routes.ts
  src/routes/productCategory.routes.ts
  src/routes/role.routes.ts
  src/routes/user.routes.ts
  src/routes/wish.routes.ts
  src/services/wish.services.ts
  src/types/test.type.ts
  src/types/wish.types.ts
  swagger.json
Labels: enhancement, Ready for review

#44 ft(search):user should be be able to search a product
  package-lock.json
  package.json
  src/__test__/initial.spec.ts
  src/app.ts
  src/controllers/search.controller.ts
  src/database/seeders/20240325212203-user.js
  src/database/seeders/20240411093719-dummy_users.js
  src/database/seeders/20240413145848-products.js
  src/middlewares/productCategory.middlewares.ts
  src/middlewares/role.middleware.ts
  src/middlewares/user.auth.ts
  src/routes/product.routes.ts
  src/routes/search.routes.ts
  src/utils/search.ts
  src/utils/string.manipulation.ts
  swagger.json
Labels: Ready for review

#40 Unlisting expired products #187300266
  package-lock.json
  package.json
  src/__test__/cronJobs/Products/checkExpiredProducts.spec.ts
  src/__test__/cronJobs/Products/expirationRoute.spec.ts
  src/__test__/cronJobs/Products/findAll.spec.ts
  src/__test__/cronJobs/Products/startCron.spec.ts
  src/__test__/initial.spec.ts
  src/__test__/matchPassword.spec.ts
  src/app.ts
  src/controllers/product.controllers.ts
  src/controllers/user.controllers.ts
  src/cronjobs/crontab.ts
  src/database/migrations/20240325142734-test_migration.js
  src/database/migrations/20240401161515-products.js
  src/database/seeders/20240411093719-dummy_users.js
  src/database/seeders/20240413145848-products.js
  src/middlewares/user.middleware.ts
  src/models/Product.ts
  src/routes/cart.routes.ts
  src/routes/product.routes.ts
  src/routes/search.routes.ts
  src/types/product.types.ts
  src/utils/cartMergeProduct.ts
  src/utils/finders.ts
  swagger.json
Labels: Ready for review

#38 #187300250:marking Items as available/unavailable
  .DS_Store
  package-lock.json
  src/.DS_Store
  src/__test__/disable-account.spec.ts
  src/__test__/initial.spec.ts
  src/__test__/otpauth.spec.ts
  src/app.ts
  src/config/passport.config.ts
  src/controllers/product.controllers.ts
  src/controllers/user.controllers.ts
  src/database/.DS_Store
  src/database/migrations/20240401161515-products.js
  src/database/migrations/20240408160241-blacklisted_tokens.js
  src/database/migrations/20240418125017-update-message-model.js
  src/database/seeders/20240325212203-user.js
  src/database/seeders/20240411093719-dummy_users.js
  src/database/seeders/20240413145848-products.js
  src/middlewares/role.middleware.ts
  src/middlewares/sellerproduct.middlewares.ts
  src/middlewares/user.auth.ts
  src/middlewares/user.middleware.ts
  src/models/Product.ts
  src/models/champs-ec-be.code-workspace
  src/routes/product.routes.ts
  src/types/product.types.ts
  src/validations/sellerProduct.validation.ts
  swagger.json
Labels: Ready for review

#47 feat(Chats): integrate socket.io for public Chats-#187300269
  .eslintrc.json
  .hintrc
  package-lock.json
  package.json
  public/index.html
  public/script.js
  public/style.css
  src/__test__/chats.spec.ts
  src/app.ts
  src/chats.ts
  src/controllers/chats.controllers.ts
  src/database/migrations/20240408160241-blacklisted_tokens.js
  src/models/messages.ts
  src/routes/chats.routes.ts
  src/socketServer.ts
  src/types/message.types.ts
  swagger.json
Labels: Ready for review

#50 bg(search):user should be able to search product
  package-lock.json
  src/__test__/cronJobs/Products/findAll.spec.ts
  src/__test__/initial.spec.ts
  src/controllers/search.controller.ts
  src/database/migrations/20240401161515-products.js
  src/models/Product.ts
  src/types/product.types.ts
  src/utils/search.ts
Labels: Ready for review

#46 #187300267 User should be prompted to change their passwords every x amount of time
  package-lock.json
  package.json
  src/__test__/cronJobs/Password/expirationRoute.spec.ts
  src/__test__/cronJobs/Password/findAll.spec.ts
  src/__test__/cronJobs/Password/startCron.spec.ts
  src/__test__/cronJobs/Products/checkExpiredProducts.spec.ts
  src/app.ts
  src/controllers/user.controllers.ts
  src/cronjobs/crontab.ts
  src/database/migrations/20240325182435-create-user.js
  src/models/user.ts
  src/routes/user.routes.ts
  src/types/user.types.ts
  src/utils/checkExpiredPassword.ts
  src/utils/finders.ts
Labels: Ready for review

#48 #187300256 reviews on product
  Dockerfile
  docker-compose.yml
  entrypoint.sh
  package-lock.json
  src/__test__/initial.spec.ts
  src/__test__/otpauth.spec.ts
  src/controllers/product.controllers.ts
  src/controllers/reviews.controller.ts
  src/controllers/user.controllers.ts
  src/database/migrations/20240401161515-products.js
  src/database/migrations/20240424101434-create-reviews.js
  src/middlewares/reviews.middlewares.ts
  src/models/Product.ts
  src/models/reviews.ts
  src/models/user.ts
  src/routes/product.routes.ts
  src/types/reviews.ts
  src/validations/review.validataion.ts
  swagger.json
Labels: Ready for review
