Repository atlp-rwanda/champs-ec-be, pull requests merged in 2024-03, with the labels that each got.

#3 #187300226 Configure ESLint and Git Pre commit hook to run tests and ESlint format
  .eslintignore
  .eslintrc.json
  .github/hooks/pre-commit
  .hound.yml
  .husky/pre-commit
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
  src/app.ts
  src/config/database.js
  src/config/db.config.ts
  src/database/migrations/20240325142734-test_migration.js
  src/database/seeders/20240325143834-tests.js
  src/models/Test.ts
  src/models/index.js
Labels: Ready for review

#6 # 187300230 Integrate CirlceCI with readme badge
  .circleci/config.yml
  .codeclimate.yml
  README.md
Labels: setting up

#14 Change database configuration
  .env.example
  package-lock.json
  src/config/db.config.ts
Labels: bug

#12 #187300237 create user signup
  .circleci/config.yml
  .gitignore
  .nyc_output/809b4e94-e669-442e-adcb-9c44e143ba32.json
  .nyc_output/processinfo/809b4e94-e669-442e-adcb-9c44e143ba32.json
  .nyc_output/processinfo/index.json
  package-lock.json
  package.json
  src/__test__/initial.spec.ts
  src/app.ts
  src/config/database.js
  src/controllers/user.controllers.ts
  src/database/migrations/20240325142734-test_migration.js
  src/database/migrations/20240325182435-create-user.js
  src/database/seeders/20240325143834-tests.js
  src/database/seeders/20240325212203-user.js
  src/middlewares/user.middleware.ts
  src/models/Test.ts
  src/models/user.ts
  src/routes/user.routes.ts
  src/types/test.type.ts
  src/types/user.types.ts
  src/utils/encrypt.ts
  src/utils/functions/redirect.ts
  src/utils/functions/token.generator.ts
  src/validations/user.validations.ts
  swagger.json
Labels: enhancement

#13 #187300240 create user login feature
  .env.example
  .sequelizerc
  package-lock.json
  package.json
  src/__test__/initial.spec.ts
  src/app.ts
  src/config/passport.config.ts
  src/controllers/user.controllers.ts
  src/middlewares/user.auth.ts
  src/middlewares/user.middleware.ts
  src/routes/user.routes.ts
  src/utils/validations/user.validations.ts
Labels: enhancement
